version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_PORT: 5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d books-service" ]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - sbs-net
    container_name: sbs-postgres
    volumes:
      - sbs-postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sbs-app
    environment:
      PORT: 3000
      ACCESS_SECRET: lkaonsdn21klf408ehfeqGOwrwqrtasMTdf23geSS
      DATABASE_URL: "postgres://postgres:root@postgres/books-service"
    ports:
      - "3000:3000"
    networks:
      - sbs-net
    depends_on:
      postgres:
        condition: service_healthy

networks:
  sbs-net:

volumes:
  sbs-postgres-data:
